### ISSUE TITLE
0.5th indexing

### ISSUE THREAD

**Issue by ChrisBeeley** [Selbosh/index0#1]
Great package, thanks!

Surely the next step would be to truly free us all from the tyranny of 0th and 1st indexing and implement the 0.5th indexing we have long dreamed of (https://twitter.com/CodeWisdom/status/806529463395741696?t=fDVaPu5zbSLwwXJcU85Ikw&s=19)

🙏

**Comment by Selbosh** [comment]
The obvious solution is an **indexn** package where we can choose any base we like at run time.

**Comment by Selbosh** [comment]
Turns out that such a package already exists: https://cran.r-project.org/package=Oarray

**Comment by ChrisBeeley** [comment]
:joy: 

Good old CRAN, something for everyone
